version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  todo-web-application:
    image: jbirtharia/todo-web-application-mysql:1.0
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      #RDS_PORT: 3306
      #RDS_DB_NAME: todos
      #RDS_USERNAME: root
      #RDS_PASSWORD: root
    networks:
      - todo-web-application-network

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - todo-web-application-network

# Volumes
volumes:
  mysql-database-data-volume:

networks:
  todo-web-application-network: